### ISSUE TITLE
2019-12-06 김민준

### ISSUE THREAD

**Issue by MINJU01103** [young2141/IRcenter#11]
1. 지역별 입학현황
마우스 오버시, 입학생->입학자로 바꾸기
예시) 2019학년도 대구지역 출신 입학자는 2,153명입니다.

2. 100명 학부생
대학원진학 부분은 변하지 않습니다. 확인부탁드립니다.

**Comment by min103jun** [comment]
입학생을 입학자로 수정하였습니다. 

2번 대학원진학 부분 이상없이 변하여서 일단 그대로 두었습니다.
