### ISSUE TITLE
2019-12-06 민준, 태영, 도영, 도한 학생

### ISSUE THREAD

**Issue by MINJU01103** [young2141/IRcenter#12]
학위수여 마우스 오버시 채워넣어야하는 문구입니다.
( ) 괄호 부분이 선택항목과 그래프 부분마다 바껴야하는 문구입니다.
하나하나 선택했을 때 문구가 이상이 없는지 꼼꼼히 확인해주세요,
그리고 하나하나 선택했을 때 문구가 이상하거나 애매한 부분 있으면 회의 때 정리해서 주세요.

[1206학위수여마우스오버.pdf](https://github.com/young2141/IRcenter/files/3930932/1206.pdf)

**Comment by young2141** [comment]
태영 파트 완료했습니다..!

**Comment by min103jun** [comment]
민준 파트 완료했습니다.
