### ISSUE TITLE
2019-12-06 김도한

### ISSUE THREAD

**Issue by MINJU01103** [young2141/IRcenter#13]
학위수여- 전공별성비 부분에 들어가면
여자, 남자 색깔 사용해서 제가 설명드린대로 잘 만들어진듯 합니다.
그런데 그때 옆에 있었던 n= , % 부분이 사라져있었습니다.
성별 검색 했을때 여자면 여자 기준으로 n= , % 를 여자막대그래프 끝나는 시점에 쭉 나타내고
(남자 수치는 생각하지 말고)
남자선택했을시, 남자 기준으로 n, % 를 나타내면 될것 같습니다.
(여자 수치는 생각하지 말고)

이 부분만 수정해주시면 될 것 같습니다.
마우스 오버 문구 또한 잊지 말아주세요.

**Comment by sphist94** [comment]
확인했습니다
