### ISSUE TITLE
2019-12-06 우영연

### ISSUE THREAD

**Issue by MINJU01103** [young2141/IRcenter#14]
영연학생
수정사항에 담지 못한 부분입니다.

학위수여-전공별 성비
제목이 전공별 학위 수여 여자 비율로 되어있는데,
성별 검색에 따라 제목이 바뀌어야할것 같습니다.
남자 선택했을때는 전공별 학위 수여 남자 비율로 띄워지게 해주세요.

또한, 여자, 남자 두개 범례 만들어 주세요!

**Comment by ooner1999** [comment]
확인했습니다.
