### ISSUE TITLE
민준, 도영, 태영, 혜진 학생 수정사항

### ISSUE THREAD

**Issue by MINJU01103** [young2141/IRcenter#28]
모두들 수고하셨습니다.
월요일 아침 9시 전까지 수정해주셔야하는 부분 올립니다.

민준학생은 기능적인 부분이 많아서, 혹시 월요일 아침까지 안되면 안된부분을 따로 카톡보내시면 감사할것 같습니다. 

[2019_12_27 수정사항.docx](https://github.com/young2141/IRcenter/files/4004404/2019_12_27.docx)

**Comment by min103jun** [comment]
6번 사항 제외하고 전부수정하였습니다. 누적형 [등록]-[학생현황]-[2] 페이지에 통합하면서 저번 회의때 피드백 받은 내용 수정하였습니다.

**Comment by young2141** [comment]
요구하신 +5범위 때문에 좀더 위로 보이는 것입니다..! 그게 마음에 안드시면 그래프랑 최대의 간격이 좀 더 벌어집니다. 어떻게 할까요
