### ISSUE TITLE
2020.01.07 (도한, 태영, 영연)

### ISSUE THREAD

**Issue by MINJU01103** [young2141/IRcenter#40]
- 자료에 적혀있는 통계연보 쪽수는 2018년도 통계연보 책 보고 작성했습니다. 2019년 통계연보 보고 만들어주세요~
- 영연학생은 주황색으로 표시된 부분만 우선 작성해주시면 돼요.
- 도한 학생이 그려야하는 그래프 2개입니다.(다른 그래프)
- 도한 학생 홈페이지에 오른쪽 부분은 영연학생이 수정하는 부분이므로 수정하면 안돼요~
- 태영 학생이 그려야하는 그래프도 2개입니다.(같은 유형의 그래프로 2개 데이터 사용)
[2020.01.07.두번째 과제.pdf](https://github.com/young2141/IRcenter/files/4029663/2020.01.07.pdf)

**Comment by young2141** [comment]
쌤 강의 시간별 교수(p24) 데이터에서 두가지 질문이 있습니다. 
 1. 데이터가 18년 2학기, 19년 1학기로 표기되어있는데, 1,2학기 합산해서 원 크기를 그리면 되는지. 
 2. 비전임교원을 다합하면 명 수가 너무 커져서 교수, 부교수같은 전임 교수의 데이터가 식별이 잘 안 된다는 점입니다. 그래서 비전임 교수 데이터를 그대로 유지해야할지도 여쭈고보고싶습니다.

**Comment by MINJU01103** [comment]
1. 영연학생이 라디오 박스를 2018학년도 2학기, 2019학년도 1학기 두 개를 만들어서 학기별로 각각 나타내는게 좋을 듯 해보입니다.

2. 비전임교원을 다 합치게 되면 전임교원 각각과 비교했을때 원 크기가 상대적으로 많이 커보이는 점에 대해서 미처 파악하지 못하였네요. 이렇게 질문 해주셔서 감사합니다! 그런데, 비전임교원이 많아서 각각 다 나타내게 되면 차트가 많이 복잡하게 보일듯해서 일단은 비전임교원은 다 합친 값으로 일단은 그려주세요! 제가 그려진 차트를 우선 보고, 많이 식별이 되지 않는다면 추후에 각각 나타내는 차트를 그리는 것을 상의해보는게 좋겠네요!

**Comment by ooner1999** [comment]
강의 시간별 교수는 주황색 부분이 아닌데, 차후에 수정하면 되는 부분인가요 ?

**Comment by young2141** [comment]
시간,교수별 인원수 그래프는 페이지가 아직 없어서 working on/html/professor_by_lecture_time.html에 제작해두었습니다.
