### ISSUE TITLE
2019-11-30 김도한

### ISSUE THREAD

**Issue by minju1103** [young2141/IRcenter#5]
도한학생
버클리에 Pell Grant Recipients 이부분에 해당하는 자료를 찾지 못하였습니다.
제가 생각하기에 미국 정부에서 학교별로 보조금을 주고
학교별로, 보조금을 받고 입학한 학생들이 몇퍼센트인지
몇년이내에 학부졸업까지 받을수 있었던 학생들이 몇퍼센트인지 나타낸 그래프인것 같습니다. 

우리나라에도 국고보조금이라는 제도가 있는데 사립대학교만 해당하고
우리학교에는 해당대상이 아니라서 그래프를 나타내는게 맞는건지 아닌건지 잘 모르겠네요.
그래서 이 그래프는 일단은 이 그래프를 만들수 있다는것에 의의를 두고 만들어봐야할것 같아요ㅠ
나중에 이 그래프가 실제로 사용 안될수도 있지만 다른 부분에서 쓰일수도 있기 때문에
버클리에 있는 차트들은 한번씩 그려보라고 센터장님께서 말씀하셔서 일단 그려보긴해야할것 같네요ㅠ
국고보조금 말고도 다른 제도를 제가 더 찾아보고 차트가 이용될수 있도록 해보겠습니다.

일단은 버클리랑 세로축, 가로축, 학교, 수치를 똑같이해서 그려봐도 될것같아요!
이 부분은 일단 제목 없이 홈페이지-등록-XY 버블차트로 들어가긴 할것 같습니다.

**Comment by sphist94** [comment]
확인했습니다
