### ISSUE TITLE
2020.01.17 지난주 수정사항(도한)

### ISSUE THREAD

**Issue by MINJU01103** [young2141/IRcenter#57]
도한학생 저번주에 그린 차트가 많이 틀렸습니다.
다시 꼼꼼히 읽어봐주세요.
그리고 전임교원 꺾은선 그리는 그래프는 두개 그려주세요.
-막대그래프 + 꺾은선 없이(자료에는 꺾은선 설명이 있는데 꺾은선 없는 차트를 여기에 넣어주세요)
-막대그래프+ 꺾은선 있게(working on에 넣어두기)

[2020.01.15 도한학생 과제.pdf](https://github.com/young2141/IRcenter/files/4075978/2020.01.15.pdf)

**Comment by sphist94** [comment]
완료했습니다.
