### ISSUE TITLE
2020-01-23 산학협력 차트 그림 (도한, 영연)

### ISSUE THREAD

**Issue by MINJU01103** [young2141/IRcenter#63]
영연학생~ 산학협력은 기타(대분류)에 넣고 산학협력 안에 소분류가 어떻게 구성되는지는 다음주에 될것 같아서 그냥 두페이지만 만들어 두시면 될것 같아요~
![산학협력 과제 그림](https://user-images.githubusercontent.com/58287049/72963354-6e4ed580-3dfa-11ea-8dc1-db68674e8770.jpg)
![산학협력 과제 그림2](https://user-images.githubusercontent.com/58287049/72963353-6e4ed580-3dfa-11ea-81e2-91be45d999b3.jpg)

**Comment by sphist94** [comment]
완료했습니다.
