### ISSUE TITLE
2019-12-06 김도한

### ISSUE THREAD

**Issue by MINJU01103** [young2141/IRcenter#8]
도한학생
새로 만들기로 한 그래프가 표 안에 버블차트로 되어있는데,
제가 생각하기에 원래 나타내고자하는 것을 저 차트를 이용해서는 잘 드러나지 않는다고 생각했습니다.
그래서 버클리 버전으로 (도한학생차트1) (도한학생차트2)
100%가로막대그래프버전으로  (도한학생차트3) (도한학생차트4)해서
두 버전을 만들어서 센터장님께 보여드리는게 좋을듯 합니다.
차트1=차트3은 대학시절 직업관련 인턴쉽은 몇 번이나 했었나요?라는 제목으로 동일한 목적을 가지고 있지만 차트유형을 달리하는 것입니다.
차트2=차트4도 마찬가지입니다.

제목이랑 범례부분은 영연학생이 작성해주기 때문에 영연학생한테 넘겨줄때
 (도한학생차트1) (도한학생차트2) (도한학생차트3) (도한학생차트4)라는 제목으로 각 차트를 넘겨주면 됩니다. 영연학생 pdf 부분에도 저 제목으로 적어놓아기 때문에 이해할것입니다.

100% 가로막대 그래프 버전이 추가되었는데,
이번주에 태영학생이 100% 세로막대 그래프를 구현해주었기 때문에
모르는 부분을 태영학생한테 물어봐도 좋을 듯 합니다.

[도한학생1206.pdf](https://github.com/young2141/IRcenter/files/3930728/1206.pdf)

**Comment by sphist94** [comment]
구현 완료했습니다.
